### ISSUE TITLE
GrammarFactory.build_default() raises TypeError

### ISSUE THREAD

**Issue by impredicative** [sebastiandev/plyse#10]
The following basic code doesn't work. It raises `TypeError`:

```python
from plyse import GrammarFactory

GrammarFactory.build_default()
```

I'm using Python 3.8 with `plyse==1.0.3` and `pyparsing==2.4.7`.

**Comment by sebastiandev** [comment]
@impredicative Thanks for spotting that. I've have pushed a fix and a [new relase](https://github.com/sebastiandev/plyse/releases/tag/1.0.4)
