### ISSUE TITLE
Could you make example for advanced nested query?

### ISSUE THREAD

**Issue by denisvolokh** [sebastiandev/plyse#4]
Could you make example for advanced nested query with custom Terms?

**Comment by sebastiandev** [comment]
Hey there, what do you mean by nested? if you mean doing something like:
`name:(foo or bar)` that is not supported, you can always decompose it as `name:foo or name:bar`
If you mean using () to make more complex expressions, then just use them, take a look at the grammar tests.
If you want to implement a different field or term, just take a look a the default implementations.

If you have some code or some specific problem, let me know.
